# fly.toml app configuration file generated for step-app-4x-yhw on 2025-07-17T13:33:39Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'step-app-4x-yhw'
primary_region = 'ord'

[build]

[[mounts]]
  source = 'data'
  destination = '/data'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
