# Optimal fly.toml - avoids CLI crash issues while maintaining safety
app = 'step-app-4x-yhw'
primary_region = 'ord'

[build]

# Single volume configuration for SQLite
[[mounts]]
  source = 'data'
  destination = '/data'
  snapshot_retention = 30  # Keep snapshots for 30 days

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = false  # Critical: Prevent data loss during auto-stop
  auto_start_machines = true
  min_machines_running = 1
  # Removed max_machines_running to avoid lease acquisition conflicts

# Simplified deployment strategy to avoid CLI crashes
[deploy]
  strategy = "rolling"
  wait_timeout = "60s"
  # Removed max_unavailable = 0 which caused lease conflicts

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1